import cookiesManager from "@/lib/service/cookies-axis/Cookies";
import { categorie_form } from "@/types/categorie_type";
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react"; // Ensure /react is imported

const apiUrl = process.env.NEXT_PUBLIC_API_URL;

export const categorieApi = createApi({
  reducerPath: "categorieApi",
  baseQuery: fetchBaseQuery({
    baseUrl: apiUrl,
    prepareHeaders: (headers) => {
      const token = cookiesManager.get("auth_token"); // Get token from cookies
      if (token) {
        headers.set("Authorization", `Bearer ${token}`); // Set the Authorization header
      }
      return headers;
    },
  }),
  endpoints: (builder) => ({
    addNewCategorie: builder.mutation<any, categorie_form>({
      query: (data) => ({
        url: "/category/add",
        method: "POST",
        body: data,
      }),
    }),
  }),
});

// Correct hook name generated by createApi
export const { useAddNewCategorieMutation } = categorieApi;
